# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Check for Lock File
      id: lock-check
      run: |
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
          echo "lock-file-exists=true" >> $GITHUB_ENV
        else
          echo "lock-file-exists=false" >> $GITHUB_ENV
        fi

    - name: Install Dependencies
      run: |
        if [ "$lock-file-exists" == "true" ]; then
          npm ci
        else
          npm install
        fi

    - name: Build Source Code
      run: npm run build --if-present

    - name: Run Tests
      run: npm test
